# -*- coding: utf-8 -*-
"""fal_api_call.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hahENf_1pJ_PBy6g16kdFnyrGy7myBIE
"""

from google.colab import userdata

FAL_KEY = userdata.get('fal_api')

# pip install fal_client

# pip install twelvelabs

# go!export FAL_KEY

saved_result = result

def get_video_url(prompt):
  import fal_client
  import os

  os.environ['FAL_KEY'] = FAL_KEY
  def on_queue_update(update):
      if isinstance(update, fal_client.InProgress):
          for log in update.logs:
            print(log["message"])

  # return "https://v3b.fal.media/files/b/lion/AoryaYzznW4osRkRqtoHi_output.mp4"
  return saved_result

  # result = fal_client.subscribe(
  #     "fal-ai/veo3",
  #     arguments={
  #         "prompt": prompt,
  #     },
  #     with_logs=True,
  #     on_queue_update=on_queue_update,
  # )
  # print(result)

  return result

get_video_url('build me the video')

from twelvelabs import TwelveLabs
from twelvelabs.indexes import IndexesCreateRequestModelsItem
from twelvelabs.tasks import TasksRetrieveResponse

labs12_api = userdata.get('labs12')
client = TwelveLabs(api_key=labs12_api)
print("Connected to TwelveLabs")

index_12_labs = '68e15e773a1b0bed6c1350cc'

index = client.indexes.create(
    index_name=index_12_labs,
    models=[
        IndexesCreateRequestModelsItem(
            model_name="marengo2.7",
            model_options=["visual", "audio"]
        )
    ]
)

# 5. Generate title, topics, and hashtags
gist = client.gist(video_id="68e1532f830688fe0b91da60",types=["title", "topic", "hashtag"])

# 6. Process the results
print(f"Title={gist.title}\nTopics={gist.topics}\nHashtags={gist.hashtags}")

